os:
  - linux
  - osx

language: rust
rust:
  - stable
cache: cargo
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test
