os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libxxf86vm-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev

language: rust
rust:
  - stable
cache: cargo
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test
